services:
  opcua-server:
    build: .
    ports:
      - "4840:4840"
    restart: unless-stopped
    volumes:
      - ./server.py:/app/server.py
    networks:
      - app-network

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"    # MQTT
      - "8080:8080"    # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app-network

networks:
  app-network:
    driver: bridge